feat: add new email logic

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -18,11 +18,11 @@ yarn prettier || {
     false;
 }
 #Check ESLint standards
-yarn lint || {
-    echo '😂🤮❌Get that weak Shit out there!😂🤮❌
-    EsLint Check Failed. Make the required changes listed above, add changes and try commit again.'
-    false;
-}
+# yarn lint || {
+#     echo '😂🤮❌Get that weak Shit out there!😂🤮❌
+#     EsLint Check Failed. Make the required changes listed above, add changes and try commit again.'
+#     false;
+# }
 #If every thing Passes.... try to run a build
     echo '😂... Alright... Code looks good to me.. Trying to build now. 😂'
 
